[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#199596"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8faff"
textColor = "#1e293b"